Arreglo[10] de Entero numeros
Entero i

Inicio
    Escriba "Prueba de Arreglos"
    Llamar nueva_linea()
    numeros[1] <- 1
    numeros[2] <- 1
    numeros[3] <- 2
    numeros[4] <- 3
    numeros[5] <- 5
    numeros[6] <- 8
    numeros[7] <- 13
    numeros[8] <- 21
    numeros[9] <- 34
    numeros[10] <- 55

    Para i <- 1 Hasta 10 Haga
      Escriba numeros[i]
          Llamar nueva_linea()
	  Fin Para
Final
